apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-forward-config
  labels:
    log-app: fluentd-forward
data:
  fluent.conf: |
    <source>
       @type forward
       port 24224
    </source>
    <source>
      @type  http
      port  9880
      body_size_limit 32m 
      keep_alive_timeout 10s 
    </source>
    <filter app.log>
      @type parser
      key_name message
      <parse> 
         @type json 
      </parse>
    </filter>
   
    <match app.log>
      @type file
      path /logs/app-%Y-%m-%d
      append true
      <format>
        @type json
      </format>
      <buffer>
        @type memory
        flush_mode immediate
      </buffer>
    </match>
    
