apiVersion: v1
kind: Service
metadata:
  name: fluentd-forward
  labels:
    log-app: fluentd-forward
spec:
  type: ClusterIP
  selector:
    app: fluentd-forward
  ports:
  - name: fluentd
    port: 9880
    targetPort: 9880
